version: '3'
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: sh
    volumes:
      - .:/usr/src/app
      - /tmp/aws_bash_profile:/root/.ash_history

  site:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    volumes:
      - ./dist:/usr/share/nginx/html
    ports:
      - "80:80"
      - "443:443"
  siteold: 
    image: nginx:alpine
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/js.power.dev.conf:/etc/nginx/sites-available/js.power.dev
      - ./nginx/js.power.dev.crt:/etc/nginx/ssl/js.power.dev.crt:ro
      - ./nginx/js.power.dev.key:/etc/nginx/ssl/js.power.dev.key:ro
    ports:
      - "80:80"
      - "8080:443"
  pipeline:
    build:
      context: .
      dockerfile: Dockerfile.pipeline
    command: sh
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /tmp/aws_bash_profile:/root/.ash_history
