version: '3'
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: sh
    volumes:
      - .:/usr/src/app
      - /tmp/aws_bash_profile:/root/.ash_history
  site: 
    image: nginx:alpine
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/js.power.dev.conf:/etc/nginx/sites-available/js.power.dev
    ports:
      - "80:80"
  pipeline:
    build:
      context: .
      dockerfile: Dockerfile.pipeline
    command: sh
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /tmp/aws_bash_profile:/root/.ash_history
